routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

Route::resource('user', 'UserController');
Route::any('user/react/{id}', 'UserController@habilita')->name('userR');
Route::any('user/desact/{id}', 'UserController@destroy')->name('userD');

Route::resource('patient', 'PacienteController');
Route::any('patient/react/{id}', 'PacienteController@habilita')->name('patientR');
Route::any('patient/desact/{id}', 'PacienteController@destroy')->name('patientD');

app/Paciente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Paciente extends Model
{
    use SoftDeletes;
    
    protected $table = 'pacientes';

    protected $fillable = [
        'nombre',
        'apellidos',
        'fecha_de_nacimiento',
        'alergias',
        'genero_id',
        'tipo_de_sangre_id'
    ];

    protected $dates = ['deleted_at'];

    public function genero(){
        return $this->belongsTo('App\Genero');
    }

    public function tipo_de_sangre(){
        return $this->belongsTo('App\Tipo_de_Sangre');
    }

    public function historiales_medicos(){
        return $this->hasMany('App\Historial_Medico');
    }

}

app/Http/Controllers/PacienteController.php
<?php

namespace App\Http\Controllers;

use App\Tipo_de_Sangre;
use App\Genero;
use App\Paciente;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PacienteController extends Controller
{
    public function index(){

        $pacientes = Paciente::withTrashed()->paginate(10);

        return view('pacientes.index')->with('pacientes', $pacientes);
    }


    public function create(){

        $generos = Genero::all();
        $tipos_de_sangre = Tipo_de_Sangre::all();
        return view('pacientes.create', ['generos'=> $generos, 'tipos_de_sangre'=> $tipos_de_sangre]);
   }

   public function store(Request $request){
       $paciente = new Paciente;
       $paciente->nombre = $request->nombre;
       $paciente->apellidos = $request->apellidos;
       $paciente->alergias = $request->alergias;
       $paciente->fecha_de_nacimiento = $request->fecha_de_nacimiento;
       $paciente->genero_id = $request->genero;
       $paciente->tipo_de_sangre_id = $request->tipo_de_sangre;

       $paciente->save();

       return redirect(action('PacienteController@index'));
   }

   public function show($id){
       $paciente = Paciente::withTrashed()->find($id);
       return view('pacientes.show', ['paciente'=>$paciente]);
   }

   public function edit($id){

        $paciente = Paciente::withTrashed()->find($id);
        $generos = Genero::all();
        $tipos_de_sangre = Tipo_de_Sangre::all();

        return view('pacientes.edit', ['generos'=> $generos, 'tipos_de_sangre'=> $tipos_de_sangre,
                                        'paciente' => $paciente]);
    }

    public function update(Request $request, $id){

        $paciente = Paciente::find($id);
        $paciente->nombre = $request->nombre;
        $paciente->apellidos = $request->apellidos;
        $paciente->alergias = $request->alergias;
        $paciente->fecha_de_nacimiento = $request->fecha_de_nacimiento;
        $paciente->genero_id = $request->genero;
        $paciente->tipo_de_sangre_id = $request->tipo_de_sangre;

        $paciente->save();

        return view('pacientes.show', ['paciente'=>$paciente]);
    }

    public function habilita($id){
        $paciente = Paciente::withTrashed()->find($id);
        $paciente->restore();
        $paciente->save();
        return redirect()->back();
    }

   public function destroy($id){

       $paciente = Paciente::find($id);
       $paciente->delete();

       return redirect()->back();
   }
}

resources/views/pacientes/create.blade.php
@extends('dashboard')

@section('scripts')
    <link rel="stylesheet" type="text/css" href="/css/semantic-ui/components/button.min.css">
    <script type="text/javascript" src="/js/semantic-ui/semantic.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/transition.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/form.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/modal.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/dropdown.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <script>
        $(document).ready(function(){
            $('.ui.dropdown').dropdown({
                forceSelection: false,
            });

            $( '#datepicker' ).datepicker({

              altField: "#datepicker",
              altFormat: "yy-mm-dd",
              changeMonth: true,
              changeYear: true,
              minDate: "-100Y",
              maxDate: new Date()

          });

            $('.ui.form').form({
              inline : true,
              on: 'blur',
              fields: {
                nombre: {
                  identifier  : 'nombre',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Nombre necesario'
                  }]
                },
                apellidos: {
                  identifier  : 'apellidos',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Apellidos necesarios'
                  }]
                },
                alergias: {
                  identifier  : 'alergias',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Sección de alergias necesaria'
                  }]
                },
                fecha_de_nacimiento: {
                  identifier  : 'fecha_de_nacimiento',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Fecha necesaria'
                  }]
                },
                genero: {
                  identifier  : 'genero',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Genero necesario'
                  }]
                },
                tipos_de_sangre: {
                  identifier  : 'tipos_de_sangre',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Tipo de sangre necesaria'
                  }]
                }
              }
            });

        });

        function registrarModal(){
            if ($('.ui.form').form('is valid')) {
                $('.small.modal').modal('show');
            }
        }
    </script>
@endsection

@section('contenido')
    <div class="ui two column stackable grid">
        <div class="thirteen wide computer eleven wide tablet column center aligned">
            <h2 class="ui header" style="margin-top:30px;">Registrar Paciente</h2>
        </div>

        <div class="three wide computer five wide tablet column">
            <div class="ui horizontal segments">

                <div class="ui segment center aligned" data-tooltip="Guardar Paciente" data-position="bottom center" onclick="registrarModal()">
                    <h3><i class="edit icon"></i></h3>
                </div>

                <div class="ui segment center aligned" onclick=window.location.href="{{action('PacienteController@index')}}" data-tooltip="Regresar" data-position="bottom center">
                    <h3><i class="arrow circle outline left icon"></i></h3>
                </div>
            </div>
        </div>
    </div>


    <form class="ui form" action="{{action('PacienteController@store')}}" method="POST" enctype="multipart/form-data" id="Registrar">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="ui three column stackable grid">
            <div class="one wide computer zero wide tablet zero wide mobile column"></div>

            <div class="thirteen wide computer sixteen wide tablet sixteen wide mobile column">

                <div class="two fields">
                    <div class="field">
                        <label>Nombre </label>
                        <input type="text" value="{{old('nombre')}}" name="nombre" placeholder="Nombre"/>
                    </div>

                    <div class="field">
                        <label>Apellidos</label>
                        <input type="text" value="{{old('apellidos')}}" name="apellidos" placeholder="Apellidos"/>
                    </div>

                </div>

                <div class="two fields">

                    <div class="field">
                        <label>Alergías</label>
                        <input type="text" value="{{old('alergias')}}" name="alergias" placeholder="Alergía al Mani" />
                    </div>

                    <div class="field">
                        <label>Género</label>
                            <select name="genero" class="ui selection dropdown" >
                                <option value="{{old('genero')}}">Seleccione un género</option>
                                @foreach($generos as $genero)
                                    <option  value="{{$genero->id}}">{{$genero->nombre}}</option>
                                @endforeach
                            </select>
                    </div>

                </div>

                <div class="two fields">

                    <div class="field">
                        <label>Fecha de nacimiento</label>
                        <input type="text" id="datepicker" value="{{old('fecha_de_nacimiento')}}" name="fecha_de_nacimiento" placeholder="yyyy-mm-dd">
                    </div>

                    <div class="field">
                        <label>Tipos de Sangre</label>
                            <select name="tipo_de_sangre" class="ui selection dropdown" >
                                <option value="{{old('tipo_de_sangre')}}">Selecciona un tipo de sangre</option>
                                @foreach($tipos_de_sangre as $tipo_de_sangre)
                                    <option  value="{{$tipo_de_sangre->id}}">{{$tipo_de_sangre->nombre}}</option>
                                @endforeach
                            </select>
                    </div>


                </div>

            </div>

        </div>

        <div class="ui small modal">
            <div class="header">Registrar Paciente</div>
            <div class="content">
                <div class="description">
                    <p>¿Seguro deseas registrar el nuevo paciente?</p>
                </div>
            </div>
            <div class="actions">
                <a class="negative ui button">Cancelar</a>
                <button class="positive submit ui button" type="submit" form="Registrar" value="registrar">
                Registrar</button>
            </div>
        </div>


    </form>


@endsection

resources/views/pacientes/edit.blade.php
@extends('dashboard')

@section('scripts')
    <link rel="stylesheet" type="text/css" href="/css/semantic-ui/components/button.min.css">
    <script type="text/javascript" src="/js/semantic-ui/semantic.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/transition.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/form.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/modal.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/dropdown.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>

    <script type="text/javascript">

      $(document).ready(function(){
        $('.ui.modal').modal();
        $('.ui.dropdown').dropdown({
            forceSelection: false,
        });

        $( '#datepicker' ).datepicker({

          altField: "#datepicker",
          altFormat: "yy-mm-dd",
          changeMonth: true,
          changeYear: true,
          minDate: "-100Y",
          maxDate: new Date()

      });

      $('.ui.form').form({
        inline : true,
        on: 'blur',
        fields: {
          nombre: {
            identifier  : 'nombre',
            rules: [{
              type   : 'empty',
              prompt : 'Nombre necesario'
            }]
          },
          apellidos: {
            identifier  : 'apellidos',
            rules: [{
              type   : 'empty',
              prompt : 'Apellidos necesarios'
            }]
          },
          alergias: {
            identifier  : 'alergias',
            rules: [{
              type   : 'empty',
              prompt : 'Sección de alergias necesaria'
            }]
          },
          fecha_de_nacimiento: {
            identifier  : 'fecha_de_nacimiento',
            rules: [{
              type   : 'empty',
              prompt : 'Fecha necesaria'
            }]
          },
          genero: {
            identifier  : 'genero',
            rules: [{
              type   : 'empty',
              prompt : 'Genero necesario'
            }]
          },
          tipos_de_sangre: {
            identifier  : 'tipos_de_sangre',
            rules: [{
              type   : 'empty',
              prompt : 'Tipo de sangre necesaria'
            }]
          }
        }
      });

        $('#msgtamano').hide();
        $('#msgextension').hide();
        $('#input').removeClass('error');

      });

      function updateModal() {
        if ($('.ui.form').form('is valid')) {
            $('.small.modal').modal('show');
        }
      }

    </script>
@endsection

@section('contenido')
    <div class="ui four column stackable grid">
        <div class="twelve wide computer eleven wide tablet column center aligned">
            <h2 class="ui header" style="margin-top:30px;">Editar Paciente</h2>
        </div>

        <div class="four wide computer five wide tablet column">
            <div class="ui horizontal segments">

                <div class="ui segment center aligned" onclick="updateModal()" data-tooltip="Actualizar Paciente" data-position="bottom center">
                    <h3><i class="save icon"></i></h3>
                </div>

                @if($paciente->deleted_at == NULL)
                    <div class="ui segment center aligned" data-tooltip="Deshabilitar Paciente" data-position="bottom center">
                        <a href="{{route('patientD' , $paciente->id)}}"><i class="red lock icon"></i></a>
                    </div>
                @else
                    <div class="ui segment center aligned" data-tooltip="Habilitar Paciente" data-position="bottom center">
                        <a href="{{route('patientR' , $paciente->id)}}"><i class=" green unlock icon"></i></a>
                    </div>
                @endif

                <div class="ui segment center aligned" onclick=onclick=window.location.href="/patient/" data-tooltip="Regresar" data-position="bottom center">
                    <h3><i class="arrow circle outline left icon"></i></h3>
                </div>
            </div>
        </div>
    </div>

    <form class="ui form" action="{{route('patient.update', $paciente->id)}}" method="POST" enctype="multipart/form-data" id="Actualizar">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{csrf_token()}}">
        <div class="ui three column stackable grid">
            <div class="one wide computer zero wide tablet zero wide mobile column"></div>

            <div class="thirteen wide computer sixteen wide tablet sixteen wide mobile column">

                <div class="two fields">
                    @if($paciente->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Nombre </label>
                        <input type="text" value="{{$paciente->nombre}}" name="nombre" placeholder="Nombre"/>
                    </div>

                    @if($paciente->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Apellidos</label>
                        <input type="text" value="{{$paciente->apellidos}}" name="apellidos" placeholder="Apellidos"/>
                    </div>

                </div>

                <div class="two fields">

                    @if($paciente->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Alergias</label>
                        <input type="text" value="{{$paciente->alergias}}" name="alergias" placeholder="Alergía al maní" />
                    </div>

                    @if($paciente->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Género</label>
                            <select name="genero" class="ui selection dropdown" >
                                <option value="{{old('tipo_de_sangre')}}">Seleccione un género</option>
                                @foreach($generos as $genero)
                                    @if($paciente->genero_id == $genero->id)
                                        <option  value="{{$genero->id}}" selected="true">{{$genero->nombre}}</option>
                                    @else
                                        <option  value="{{$genero->id}}">{{$genero->nombre}}</option>
                                    @endif
                                @endforeach
                            </select>
                    </div>


                </div>

                <div class="two fields">

                    @if($paciente->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Fecha de nacimiento</label>
                        <input type="text" id="datepicker" value="{{$paciente->fecha_de_nacimiento}}" name="fecha_de_nacimiento" placeholder="yyyy-mm-dd">
                    </div>

                    @if($paciente->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Tipos de Sangre</label>
                            <select name="tipo_de_sangre" class="ui selection dropdown" >
                                <option value="{{old('tipo_de_sangre')}}">Selecciona un tipo de sangre</option>
                                @foreach($tipos_de_sangre as $tipo_de_sangre)
                                    @if($paciente->tipo_de_sangre_id == $tipo_de_sangre->id)
                                        <option  value="{{$tipo_de_sangre->id}}" selected="true">{{$tipo_de_sangre->nombre}}</option>
                                    @else
                                        <option  value="{{$tipo_de_sangre->id}}">{{$tipo_de_sangre->nombre}}</option>
                                    @endif
                                @endforeach
                            </select>
                    </div>


                </div>

            </div>

        </div>

        <div class="ui small modal">
            <div class="header">Actualizar Paciente</div>
            <div class="content">
                <div class="description">
                    <p>¿Seguro deseas actualizar el paciente?</p>
                </div>
            </div>
            <div class="actions">
                <a class="negative ui button">Cancelar</a>
                <button class="positive submit ui button" type="submit" form="Actualizar" value="actualizar">
                Actualizar</button>
            </div>
        </div>

    </form>

@endsection

resources/views/pacientes/index.blade.php
@extends('dashboard')

@section('scripts')
    <script type="text/javascript" src="/js/semantic-ui/components/transition.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/form.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/modal.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/sortT.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/semantic.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function(){
          $('table').tablesort();
          $('.ui.form').form();
          $('.ui.modal').modal();
        });
        </script>


@endsection

@section('contenido')
    <div class="ui four column stackable grid">
        <div class="fourteen wide computer twelve wide tablet column">
            <h2 class="ui header" style="margin-top:30px; margin-bottom:30px;">Paciente</h2>
        </div>

        <div class="two wide computer four wide tablet column">
            <div class="ui horizontal segments">

                <div class="ui segment center aligned" onclick=window.location.href="{{action('PacienteController@create')}}" data-tooltip="Crear Paciente" data-position="bottom center">
                    <h3><i class="add user icon"></i></h3>
                </div>
            </div>
        </div>


    </div>

    <div class="ui row">

            <table class="ui fixed sortable celled table">
                <thead>
                    <tr>
                        <th class="three wide sorted descending center aligned">Nombre</th>
                        <th class="three wide sorted descending center aligned">Apellidos</th>
                        <th class="three wide sorted descending center aligned">Tipo de Sangre</th>
                        <th class="two wide sorted descendingd center aligned">Género</th>
                        <th class="two wide center aligned" colspan="3">Opciones</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($pacientes as $paciente)
                        @if($paciente->deleted_at != NULL)
                            <tr class="negative">
                        @else
                            <tr class="">
                        @endif

                        <td>{{$paciente->nombre}}</td>
                        <td>{{$paciente->apellidos}}</td>
                        <td>{{$paciente->tipo_de_sangre->nombre}}</td>
                        <td>{{$paciente->genero->nombre}}</td>
                        <td class="center aligned selectable">
                            <a href="{{action('PacienteController@show' , $paciente->id)}}"><i class="info circle icon"></i></a>
                        </td>
                        <td class="center aligned selectable">
                            <a href="{{action('PacienteController@edit' , $paciente->id)}}"><i class="edit icon"></i></a>
                        </td>

                        @if($paciente->deleted_at == NULL)
                            <td class="center aligned selectable">
                                <a href="{{route('patientD' , $paciente->id)}}"><i class="red lock icon"></i></a>
                            </td>
                        @else
                            <td class="center aligned selectable">
                                <a href="{{route('patientR' , $paciente->id)}}"><i class=" green unlock icon"></i></a>
                            </td>
                        @endif

                        </tr>
                    @endforeach
                </tbody>

                <tfoot>
                    <tr>
                        <th colspan="7">
                            <div class="ui right floated pagination menu">
                            <a href="{{$pacientes->previousPageUrl()}}" class="icon item">
                                <i class="left chevron icon"></i>
                            </a>

                            @for($i = 1; $i <= $pacientes->lastPage(); $i++)
                                <a href="{{$pacientes->url($i)}}" class="item"> {{$i}} </a>
                            @endfor

                            <a href="{{$pacientes->nextPageUrl()}}" class="icon item">
                                <i class="right chevron icon"></i>
                            </a>
                            </div>
                        </th>
                    </tr>
                </tfoot>

            </table>

        </div>


@endsection

resources/views/pacientes/show.blade.php
@extends('dashboard')

@section('scripts')
    <script type="text/javascript" src="/js/semantic-ui/components/transition.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/dropdown.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/modal.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/form.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/semantic.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>

    <script type="text/javascript">

      $(document).ready(function(){
        $('.ui.modal').modal();
        $('.ui.dropdown').dropdown({
            forceSelection: false,
        });
    });


    </script>
@endsection

@section('contenido')
    <div class="ui four column stackable grid">
        <div class="twelve wide computer eleven wide tablet column center aligned">
            <h2 class="ui header" style="margin-top:30px;">Paciente {{$paciente->nombre}} {{$paciente->apellidos}}</h2>
        </div>

        <div class="four wide computer five wide tablet column">
            <div class="ui horizontal segments">

                <div class="ui segment center aligned"  data-tooltip="Actualizar Paciente" data-position="bottom center">
                    <h3><a href="{{action('PacienteController@edit' , $paciente->id)}}"><i class="edit icon"></i></a></i></h3>
                </div>

                @if($paciente->deleted_at == NULL)
                    <div class="ui segment center aligned" data-tooltip="Deshabilitar Usuario" data-position="bottom center">
                        <a href="{{route('patientD' , $paciente->id)}}"><i class="red lock icon"></i></a>
                    </div>
                @else
                    <div class="ui segment center aligned" data-tooltip="Habilitar Usuario" data-position="bottom center">
                        <a href="{{route('patientR' , $paciente->id)}}"><i class=" green unlock icon"></i></a>
                    </div>
                @endif

                <div class="ui segment center aligned" onclick=window.location.href="/patient/" data-tooltip="Regresar" data-position="bottom center">
                    <h3><i class="arrow circle outline left icon"></i></h3>
                </div>
            </div>
        </div>
    </div>

    <form class="ui form" action="{{route('patient.update', $paciente->id)}}" method="POST" enctype="multipart/form-data" id="Actualizar">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{csrf_token()}}">
        <div class="ui three column stackable grid">
            <div class="one wide computer zero wide tablet zero wide mobile column"></div>

            <div class="thirteen wide computer sixteen wide tablet sixteen wide mobile column">

                <div class="ui segments">
                    <div class="ui horizontal segments">
                        <div class="ui segment">
                            <h4>Nombre:</h4><p>{{$paciente->nombre}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Apellidos:</h4><p>{{$paciente->apellidos}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Alergías</h4><p>{{$paciente->alergias}}</p>
                        </div>
                    </div>
                    <div class="ui horizontal segments">
                        <div class="ui segment">
                            <h4>Fecha de Nacimiento:</h4><p>{{$paciente->fecha_de_nacimiento}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Género:</h4><p>{{$paciente->genero->nombre}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Tipo de Sangre:</h4><p>{{$paciente->tipo_de_sangre->nombre}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Paciente:</h4>
                            <p>
                                @if($paciente->deleted_at == NULL)
                                Activo
                                @else
                                Inactivo
                                @endif
                            </p>
                        </div>
                    </div>
              </div>

            </div>

        </div>

@endsection