routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

Route::resource('user', 'UserController');
Route::any('user/react/{id}', 'UserController@habilita')->name('userR');
Route::any('user/desact/{id}', 'UserController@destroy')->name('userD');

Route::resource('patient', 'PacienteController');
Route::any('patient/react/{id}', 'PacienteController@habilita')->name('patientR');
Route::any('patient/desact/{id}', 'PacienteController@destroy')->name('patientD');

resources/views/usuarios/create.blade.php
@extends('dashboard')

@section('scripts')
    <link rel="stylesheet" type="text/css" href="/css/semantic-ui/components/button.min.css">
    <script type="text/javascript" src="/js/semantic-ui/semantic.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/transition.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/form.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/modal.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/dropdown.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <script>
        $(document).ready(function(){
            $('.ui.dropdown').dropdown({
                forceSelection: false,
            });

            $( '#datepicker' ).datepicker({

              altField: "#datepicker",
              altFormat: "yy-mm-dd",
              changeMonth: true,
              changeYear: true,
              minDate: "-100Y",
              maxDate: new Date()

          });

            $('.ui.form').form({
              inline : true,
              on: 'blur',
              fields: {
                nombre: {
                  identifier  : 'nombre',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Nombre necesario'
                  }]
                },
                apellidos: {
                  identifier  : 'apellidos',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Apellidos necesarios'
                  }]
                },
                email: {
                  identifier  : 'email',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Correo Electrónico necesario'
                  }]
                },
                fecha_de_nacimiento: {
                  identifier  : 'fecha_de_nacimiento',
                  rules: [{
                    type   : 'empty',
                    prompt : 'Fecha necesaria'
                  }]
                }
              }
            });

        });

        function registrarModal(){
            if ($('.ui.form').form('is valid')) {
                $('.small.modal').modal('show');
            }
        }
    </script>
@endsection

@section('contenido')
    <div class="ui two column stackable grid">
        <div class="thirteen wide computer eleven wide tablet column center aligned">
            <h2 class="ui header" style="margin-top:30px;">Registrar Usuario</h2>
        </div>

        <div class="three wide computer five wide tablet column">
            <div class="ui horizontal segments">

                <div class="ui segment center aligned" data-tooltip="Guardar Usuario" data-position="bottom center" onclick="registrarModal()">
                    <h3><i class="edit icon"></i></h3>
                </div>

                <div class="ui segment center aligned" onclick=window.location.href="{{action('UserController@index')}}" data-tooltip="Regresar" data-position="bottom center">
                    <h3><i class="arrow circle outline left icon"></i></h3>
                </div>
            </div>
        </div>
    </div>


    <form class="ui form" action="{{action('UserController@store')}}" method="POST" enctype="multipart/form-data" id="Registrar">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="ui three column stackable grid">
            <div class="one wide computer zero wide tablet zero wide mobile column"></div>

            <div class="thirteen wide computer sixteen wide tablet sixteen wide mobile column">

                <div class="two fields">
                    <div class="field">
                        <label>Nombre </label>
                        <input type="text" value="{{old('nombre')}}" name="nombre" placeholder="Nombre"/>
                    </div>

                    <div class="field">
                        <label>Apellidos</label>
                        <input type="text" value="{{old('apellidos')}}" name="apellidos" placeholder="Apellidos"/>
                    </div>

                </div>

                <div class="three fields">

                    <div class="field">
                        <label>Correo Electrónico</label>
                        <input type="email" value="{{old('email')}}" name="email" placeholder="ejemplo@ejemplo.com" />
                    </div>

                    <div class="field">
                        <label>Contraseña</label>
                        <input type="password" placeholder="min 8 carácteres" name="password" />
                    </div>

                    <div class="field">
                        <label>Verificar Contraseña</label>
                        <input type="password" placeholder="min 8 carácteres" name="v_password" />
                    </div>
                </div>

                <div class="two fields">

                    <div class="field">
                        <label>Fecha de nacimiento</label>
                        <input type="text" id="datepicker" value="{{old('fecha_de_nacimiento')}}" name="fecha_de_nacimiento" placeholder="yyyy-mm-dd">
                    </div>

                    <div class="field">
                        <label>Rol</label>
                            <select name="rol" class="ui selection dropdown" >
                                <option value="{{old('rol')}}">Selecciona un rol</option>
                                @foreach($roles as $rol)
                                    <option  value="{{$rol->id}}">{{$rol->nombre}}</option>
                                @endforeach
                            </select>
                    </div>


                </div>

            </div>

        </div>

        <div class="ui small modal">
            <div class="header">Registrar Usuario</div>
            <div class="content">
                <div class="description">
                    <p>¿Seguro deseas registrar el nuevo usuario?</p>
                </div>
            </div>
            <div class="actions">
                <a class="negative ui button">Cancelar</a>
                <button class="positive submit ui button" type="submit" form="Registrar" value="registrar">
                Registrar</button>
            </div>
        </div>
        <div class="ui error message"></div>
        @if(count($errors) > 0)
        <div class="ui negative message">
            <ul class="ui list">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

    </form>


@endsection

resources/views/usuarios/edit.blade.php
@extends('dashboard')

@section('scripts')
    <link rel="stylesheet" type="text/css" href="/css/semantic-ui/components/button.min.css">
    <script type="text/javascript" src="/js/semantic-ui/semantic.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/transition.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/form.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/modal.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/dropdown.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>

    <script type="text/javascript">

      $(document).ready(function(){
        $('.ui.modal').modal();
        $('.ui.dropdown').dropdown({
            forceSelection: false,
        });

        $( '#datepicker' ).datepicker({

          altField: "#datepicker",
          altFormat: "yy-mm-dd",
          changeMonth: true,
          changeYear: true,
          minDate: "-100Y",
          maxDate: new Date()

      });

        $('.ui.form').form({
          inline : true,
          on: 'blur',
          fields: {
            nombre: {
              identifier  : 'nombre',
              rules: [{
                type   : 'empty',
                prompt : 'Nombre necesario'
              }]
            },
            apellidos: {
              identifier  : 'apellidos',
              rules: [{
                type   : 'empty',
                prompt : 'Apellidos necesarios'
              }]
            },
            email: {
              identifier  : 'email',
              rules: [{
                type   : 'empty',
                prompt : 'Correo Electrónico necesario'
              }]
            },
            fecha_de_nacimiento: {
              identifier  : 'fecha_de_nacimiento',
              rules: [{
                type   : 'empty',
                prompt : 'Fecha necesaria'
              }]
            }
          }
        });

        $('#msgtamano').hide();
        $('#msgextension').hide();
        $('#input').removeClass('error');

      });

      function updateModal() {
        if ($('.ui.form').form('is valid')) {
            $('.small.modal').modal('show');
        }
      }

    </script>
@endsection

@section('contenido')
    <div class="ui four column stackable grid">
        <div class="twelve wide computer eleven wide tablet column center aligned">
            <h2 class="ui header" style="margin-top:30px;">Editar Usuario</h2>
        </div>

        <div class="four wide computer five wide tablet column">
            <div class="ui horizontal segments">

                <div class="ui segment center aligned" onclick="updateModal()" data-tooltip="Actualizar Usuario" data-position="bottom center">
                    <h3><i class="save icon"></i></h3>
                </div>

                @if($user->deleted_at == NULL)
                    <div class="ui segment center aligned" data-tooltip="Deshabilitar Usuario" data-position="bottom center">
                        <a href="{{route('userD' , $user->id)}}"><i class="red lock icon"></i></a>
                    </div>
                @else
                    <div class="ui segment center aligned" data-tooltip="Habilitar Usuario" data-position="bottom center">
                        <a href="{{route('userR' , $user->id)}}"><i class=" green unlock icon"></i></a>
                    </div>
                @endif

                <div class="ui segment center aligned" onclick=onclick=window.location.href="/user/" data-tooltip="Regresar" data-position="bottom center">
                    <h3><i class="arrow circle outline left icon"></i></h3>
                </div>
            </div>
        </div>
    </div>

    <form class="ui form" action="{{route('user.update', $user->id)}}" method="POST" enctype="multipart/form-data" id="Actualizar">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{csrf_token()}}">
        <div class="ui three column stackable grid">
            <div class="one wide computer zero wide tablet zero wide mobile column"></div>

            <div class="thirteen wide computer sixteen wide tablet sixteen wide mobile column">

                <div class="two fields">
                    @if($user->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Nombre </label>
                        <input type="text" value="{{$user->nombre}}" name="nombre" placeholder="Nombre"/>
                    </div>

                    @if($user->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Apellidos</label>
                        <input type="text" value="{{$user->apellidos}}" name="apellidos" placeholder="Apellidos"/>
                    </div>

                </div>

                <div class="three fields">

                    @if($user->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Correo Electrónico</label>
                        <input type="email" value="{{$user->email}}" name="email" placeholder="ejemplo@ejemplo.com" />
                    </div>

                    @if($user->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Contraseña</label>
                        <input type="password" placeholder="min 8 carácteres" name="password" />
                    </div>

                    @if($user->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Verificar Contraseña</label>
                        <input type="password" placeholder="min 8 carácteres" name="v_password" />
                    </div>
                </div>

                <div class="two fields">

                    @if($user->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Fecha de nacimiento</label>
                        <input type="text" id="datepicker" value="{{$user->fecha_de_nacimiento}}" name="fecha_de_nacimiento" placeholder="yyyy-mm-dd">
                    </div>

                    @if($user->deleted_at != NULL)
                        <div class="disabled field">
                    @else
                        <div class="field">
                    @endif
                        <label>Rol</label>
                            <select name="rol" class="ui selection dropdown" >
                                <option value="{{old('rol')}}">Selecciona un rol</option>
                                @foreach($roles as $rol)
                                    @if($user->rol_id == $rol->id)
                                        <option  value="{{$rol->id}}" selected="true">{{$rol->nombre}}</option>
                                    @else
                                        <option  value="{{$rol->id}}">{{$rol->nombre}}</option>
                                    @endif
                                @endforeach
                            </select>
                    </div>


                </div>

            </div>

        </div>

        <div class="ui small modal">
            <div class="header">Actualizar Usuario</div>
            <div class="content">
                <div class="description">
                    <p>¿Seguro deseas actualizar el usuario?</p>
                </div>
            </div>
            <div class="actions">
                <a class="negative ui button">Cancelar</a>
                <button class="positive submit ui button" type="submit" form="Actualizar" value="actualizar">
                Actualizar</button>
            </div>
        </div>
        <div class="ui error message"></div>
        @if(count($errors) > 0)
        <div class="ui negative message">
            <ul class="ui list">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

    </form>

@endsection

resources/views/usuarios/index.blade.php
@extends('dashboard')

@section('scripts')
    <script type="text/javascript" src="/js/semantic-ui/components/transition.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/form.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/modal.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/sortT.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/semantic.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function(){
          $('table').tablesort();
          $('.ui.form').form();
          $('.ui.modal').modal();
        });
        </script>


@endsection

@section('contenido')
    <div class="ui four column stackable grid">
        <div class="fourteen wide computer twelve wide tablet column">
            <h2 class="ui header" style="margin-top:30px; margin-bottom:30px;">Usuarios</h2>
        </div>

        <div class="two wide computer four wide tablet column">
            <div class="ui horizontal segments">

                <div class="ui segment center aligned" onclick=window.location.href="{{action('UserController@create')}}" data-tooltip="Crear Usuario" data-position="bottom center">
                    <h3><i class="add user icon"></i></h3>
                </div>
            </div>
        </div>


    </div>

    <div class="ui row">

            <table class="ui fixed sortable celled table">
                <thead>
                    <tr>
                        <th class="three wide sorted descending center aligned">Nombre</th>
                        <th class="three wide sorted descending center aligned">Apellidos</th>
                        <th class="three wide sorted descending center aligned">Correo Eletrónico</th>
                        <th class="two wide sorted descendingd center aligned">Rol de Usuario</th>
                        <th class="two wide center aligned" colspan="3">Opciones</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach($users as $user)
                        @if($user->deleted_at != NULL)
                            <tr class="negative">
                        @else
                            <tr class="">
                        @endif

                        <td>{{$user->nombre}}</td>
                        <td>{{$user->apellidos}}</td>
                        <td>{{$user->email}}</td>
                        <td>{{$user->rol->nombre}}</td>
                        <td class="center aligned selectable">
                            <a href="{{action('UserController@show' , $user->id)}}"><i class="info circle icon"></i></a>
                        </td>
                        <td class="center aligned selectable">
                            <a href="{{action('UserController@edit' , $user->id)}}"><i class="edit icon"></i></a>
                        </td>

                        @if($user->deleted_at == NULL)
                            <td class="center aligned selectable">
                                <a href="{{route('userD' , $user->id)}}"><i class="red lock icon"></i></a>
                            </td>
                        @else
                            <td class="center aligned selectable">
                                <a href="{{route('userR' , $user->id)}}"><i class=" green unlock icon"></i></a>
                            </td>
                        @endif

                        </tr>
                    @endforeach
                </tbody>

                <tfoot>
                    <tr>
                        <th colspan="7">
                            <div class="ui right floated pagination menu">
                            <a href="{{$users->previousPageUrl()}}" class="icon item">
                                <i class="left chevron icon"></i>
                            </a>

                            @for($i = 1; $i <= $users->lastPage(); $i++)
                                <a href="{{$users->url($i)}}" class="item"> {{$i}} </a>
                            @endfor

                            <a href="{{$users->nextPageUrl()}}" class="icon item">
                                <i class="right chevron icon"></i>
                            </a>
                            </div>
                        </th>
                    </tr>
                </tfoot>

            </table>

        </div>


@endsection

resources/views/usuarios/show.blade.php
@extends('dashboard')

@section('scripts')
    <script type="text/javascript" src="/js/semantic-ui/components/transition.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/dropdown.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/modal.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/components/form.min.js"></script>
    <script type="text/javascript" src="/js/semantic-ui/semantic.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>

    <script type="text/javascript">

      $(document).ready(function(){
        $('.ui.modal').modal();
        $('.ui.dropdown').dropdown({
            forceSelection: false,
        });
    });


    </script>
@endsection

@section('contenido')
    <div class="ui four column stackable grid">
        <div class="twelve wide computer eleven wide tablet column center aligned">
            <h2 class="ui header" style="margin-top:30px;">Usuario {{$user->nombre}} {{$user->apellidos}}</h2>
        </div>

        <div class="four wide computer five wide tablet column">
            <div class="ui horizontal segments">

                <div class="ui segment center aligned"  data-tooltip="Actualizar Usuario" data-position="bottom center">
                    <h3<a href="{{action('UserController@edit' , $user->id)}}"><i class="edit icon"></i></a></i></h3>
                </div>

                @if($user->deleted_at == NULL)
                    <div class="ui segment center aligned" data-tooltip="Deshabilitar Usuario" data-position="bottom center">
                        <a href="{{route('userD' , $user->id)}}"><i class="red lock icon"></i></a>
                    </div>
                @else
                    <div class="ui segment center aligned" data-tooltip="Habilitar Usuario" data-position="bottom center">
                        <a href="{{route('userR' , $user->id)}}"><i class=" green unlock icon"></i></a>
                    </div>
                @endif

                <div class="ui segment center aligned" onclick=onclick=window.location.href="/user/" data-tooltip="Regresar" data-position="bottom center">
                    <h3><i class="arrow circle outline left icon"></i></h3>
                </div>
            </div>
        </div>
    </div>

    <form class="ui form" action="{{route('user.update', $user->id)}}" method="POST" enctype="multipart/form-data" id="Actualizar">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{csrf_token()}}">
        <div class="ui three column stackable grid">
            <div class="one wide computer zero wide tablet zero wide mobile column"></div>

            <div class="thirteen wide computer sixteen wide tablet sixteen wide mobile column">

                <div class="ui segments">
                    <div class="ui horizontal segments">
                        <div class="ui segment">
                            <h4>Nombre:</h4><p>{{$user->nombre}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Apellidos:</h4><p>{{$user->apellidos}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Correo electrónico</h4><p>{{$user->email}}</p>
                        </div>
                    </div>
                    <div class="ui horizontal segments">
                        <div class="ui segment">
                            <h4>Fecha de Nacimiento:</h4><p>{{$user->fecha_de_nacimiento}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Rol de Usuario:</h4><p>{{$user->rol->nombre}}</p>
                        </div>
                        <div class="ui segment">
                            <h4>Usuario:</h4>
                            <p>
                                @if($user->deleted_at == NULL)
                                Activo
                                @else
                                Inactivo
                                @endif
                            </p>
                        </div>
                    </div>
              </div>

            </div>

        </div>

@endsection